### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by zy-serguei** [dinony/od-virtualscroll#8]
If I have multiple instances of od-virtualscroll is there a way to determine which instance triggered an observable on ScrollObservableService (scrollWin$, createItem$, etc.)?

**Comment by dinony** [comment]
AH, thank you serguei, you're right! I did not think of this.. will come up with a solution soon.

**Comment by dinony** [comment]
Turns out that it is already supported. You have to make use of the hierarchical Injectors concept in Angular (https://angular.io/guide/hierarchical-dependency-injection). 

The `ScrollObservableService` is registered on the `VirtualScrollModule` by default, so it's available on the root injector.
However, if you have multiple instances of the scroll component, a singleton instance of the `ScrollObservableService` is not enough. 
You can register the service on the wrapping component, via providers property in the `@Component` decorator, so that the injector bubbling will stop bubbling up to the root injector and will serve the right instance of the `ScrollObservableService`.

Check the `feature/testMultiInstances ` branch for a simple example.

Please feel free to open up this issue again, if you find something else.
